[package]
name = "rosdraw"
version = "0.1.0"
authors = ["Sergey Kacheev <s.kacheev@gmail.com>"]
edition = "2018"

[dependencies]
nannou = "0.8.0"
conrod = "0.61"
log = "^0.4"
env_logger = "^0.6"
posixmq = "0.1.1"
